### ISSUE TITLE
added Nvidia's binaries folder, getting No module named 'PySide2' error opening a simple usd file.

### ISSUE THREAD

**Issue by Ahmed-Hindy** [sssooonnnggg/usdc-viewer#2]
I added the Nvidia compiled binaries to the "path to op[enusd library" then tried to open a simple .usd ascii file but it failed

here is the usd I am trying to open, simple save the text as a .usd file

```
#usda 1.0
(
    "Exported from Adobe Substance 3D Painter 8.3.0"
    defaultPrim = "root"
    subLayers = [
        @./MeetMat.material.usda@
    ]
)

def "root" (
    prepend references = @./MeetMat.geo.usd@
)
{
}

```

and here is the error log:
```
Command failed: usdview f:\Users\Ahmed Hindy\Documents\Adobe\Adobe Substance 3D Painter\export\MeetMat.usd
Traceback (most recent call last):
  File "G:\Projects\USD Scenes\usd.py310.windows-x86_64.usdview.release@0.24.05-tc.859+release.2864f3d0\bin\usdview", line 28, in <module>
    import pxr.Usdviewq as Usdviewq
  File "G:\Projects\USD Scenes\usd.py310.windows-x86_64.usdview.release@0.24.05-tc.859+release.2864f3d0\lib\python\pxr\Usdviewq\__init__.py", line 32, in <module>
    from .qt import QtWidgets, QtCore
  File "G:\Projects\USD Scenes\usd.py310.windows-x86_64.usdview.release@0.24.05-tc.859+release.2864f3d0\lib\python\pxr\Usdviewq\qt.py", line 42, in <module>
    PySideModule = GetPySideModule()
  File "G:\Projects\USD Scenes\usd.py310.windows-x86_64.usdview.release@0.24.05-tc.859+release.2864f3d0\lib\python\pxr\Usdviewq\qt.py", line 31, in GetPySideModule
    from . import attributeValueEditorUI
  File "G:\Projects\USD Scenes\usd.py310.windows-x86_64.usdview.release@0.24.05-tc.859+release.2864f3d0\lib\python\pxr\Usdviewq\attributeValueEditorUI.py", line 11, in <module>
    from PySide2.QtCore import *
ModuleNotFoundError: No module named 'PySide2'
```

**Comment by sssooonnnggg** [comment]
If you want to use usdview, you should install python dependencies manually such as PySide and etc
